AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  catalog-update-processor

  Sample SAM Template for catalog-update-processor

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  PromotionsPublisherHandler:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../CatalogUpdateProcessor
      Handler: poc.amitk.lambda.java.eventbridge.promotions.PromotionsPublisherHandler::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          POWERTOOLS_LOG_LEVEL: INFO
          POWERTOOLS_SERVICE_NAME: catalog-update-processor
      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName: ProductCatalogEventBus
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt PromotionsPublisherHandlerDLQ.Arn
      Events:
        ProductUpdatedEvent:
#         Sam template Function > Event Source > EventBridgeRule https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-eventbridgerule.html
          Type: EventBridgeRule # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            EventBusName: ProductCatalogEventBus
            Pattern:
              source:
                - com.amitk.catalogservice
            DeadLetterConfig:
#              With the queue logical id the dlq is created automatically
              Type: SQS
              QueueLogicalId: ProductUdpatedEventForPromotionsDLQ
            RetryPolicy:
              MaximumEventAgeInSeconds: 60
              MaximumRetryAttempts: 1


  PromotionsPublisherHandlerDLQ:
    Type: AWS::SQS::Queue


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PromotionsPublisherHandlerDLQQueueUrl:
    Description: "PromotionsPublisherHandlerDLQ queue-url"
    Value: !GetAtt PromotionsPublisherHandlerDLQ.QueueUrl
  PromotionsPublisherHandlerDLQQueueName:
    Description: "PromotionsPublisherHandlerDLQ queue-name"
    Value: !GetAtt PromotionsPublisherHandlerDLQ.QueueName
