AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  springboot-lambda

  Sample SAM Template for springboot-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 2048

Parameters:
  LambdaSubnetId:
    Type: String
    Description: The subnet the lambda function will run inside of the vpc
  LambdaSecurityGroupId:
    Type: String
    Description: The security group the function will use (needs access to secrets manager service, mysql)
  RdsMysqlSecretArn:
    Type: String
    Description: The credentials for mysql rds database
  RdsMysqlSecretId:
    Type: String
    Description: The secret id for mysql rds database credentials

Resources:
  ProductCatalogGetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: product-catalog-sb-api
      Handler: poc.amitk.lambda.sb.api.infra.StreamLambdaHandler::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DATASOURCE_SECRET_ID: !Ref RdsMysqlSecretId
          MAIN_CLASS: poc.amitk.lambda.sb.api.ProductCatalogSbApiApplication
      VpcConfig:
        SubnetIds:
          - !Ref LambdaSubnetId
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref RdsMysqlSecretArn
      SnapStart:
        ApplyOn: PublishedVersions
      AutoPublishAlias: production
      Events:
        GetAllProducts:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ProductCatalogApi:
    Description: "API Gateway endpoint URL for Prod stage for product catalog sb function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/products/1"